# Generated by Django 5.2.10 on 2026-05-11 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Public referral handle used in /r/<slug>/ URLs.', max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('stripe_connect_account_id', models.CharField(blank=True, max_length=120)),
                ('stripe_connect_onboarded', models.BooleanField(default=False)),
                ('stripe_connect_payouts_enabled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='AffiliateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('website_or_handle', models.CharField(max_length=255)),
                ('audience_size', models.CharField(blank=True, choices=[('under_1k', 'Under 1,000'), ('1k_10k', '1,000 – 10,000'), ('10k_100k', '10,000 – 100,000'), ('over_100k', '100,000+')], max_length=24)),
                ('promotion_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_context', models.JSONField(blank=True, default=dict)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='affiliates.affiliate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_affiliate_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=16)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=120)),
                ('stripe_destination_account', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='affiliates.affiliate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fraud_flag', models.CharField(choices=[('none', 'Clean'), ('same_domain', 'Same email domain as affiliate'), ('same_ip', 'Same IP as affiliate'), ('manual_review', 'Flagged for manual review'), ('rejected', 'Rejected')], default='none', max_length=24)),
                ('fraud_note', models.CharField(blank=True, max_length=255)),
                ('first_payment_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='affiliates.affiliate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('first_payment', 'First payment'), ('recurring', 'Recurring'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending hold'), ('approved', 'Approved for payout'), ('paid', 'Paid'), ('voided', 'Voided'), ('on_hold', 'On hold for review')], default='pending', max_length=16)),
                ('gross_amount_cents', models.PositiveIntegerField(help_text='Stripe payment amount in cents (what the customer paid).')),
                ('commission_rate_pct', models.PositiveSmallIntegerField(help_text='Rate applied (e.g. 25 for first payment, 15 for recurring).')),
                ('commission_amount_cents', models.PositiveIntegerField(help_text='Commission owed in cents (gross × rate).')),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('stripe_event_id', models.CharField(max_length=120, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=120)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=120)),
                ('release_at', models.DateTimeField(help_text='When the 30-day hold clears and the commission becomes payable.')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliates.affiliate')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_commissions', to=settings.AUTH_USER_MODEL)),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='affiliates.payout')),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='affiliates.referralattribution')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referer', models.CharField(blank=True, max_length=512)),
                ('landing_path', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliates.affiliate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='referralattribution',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='affiliates.referralclick'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['affiliate', 'status'], name='affiliates__affilia_350b30_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['affiliate', 'status'], name='affiliates__affilia_3657d2_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['status', 'release_at'], name='affiliates__status_ba94f8_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclick',
            index=models.Index(fields=['affiliate', '-created_at'], name='affiliates__affilia_09c63d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['affiliate', '-created_at'], name='affiliates__affilia_430709_idx'),
        ),
    ]
