# Generated by Django 5.2.10 on 2026-03-29 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('leads', '0005_workspaceplan_workspacesubscription_usagerecord'),
        ('tools', '0007_auditchangereport_workspaceauditschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('output_type', models.CharField(choices=[('service_page', 'Service Page'), ('landing_page', 'Landing Page'), ('article', 'Article'), ('answer_block', 'Answer Block')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('applied', 'Applied'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('page_goal', models.CharField(blank=True, max_length=255)),
                ('offer_summary', models.CharField(blank=True, max_length=255)),
                ('search_intent', models.CharField(blank=True, max_length=120)),
                ('target_keywords', models.JSONField(blank=True, default=list)),
                ('body', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=255)),
                ('faq_items', models.JSONField(blank=True, default=list)),
                ('suggested_internal_links', models.JSONField(blank=True, default=list)),
                ('keywords_used', models.JSONField(blank=True, default=list)),
                ('prompt_context', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('validation_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='leads.clientproject')),
                ('source_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='tools.auditrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
