# Generated by Django 5.2.10 on 2026-03-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_generatedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='applied_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_drafts', to='content.article'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='applied_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_drafts', to='content.service'),
        ),
    ]
