# Generated by Django 5.2.10 on 2026-03-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_generatedcontent_applied_article_and_more'),
        ('seo', '0005_seocompetitor_metadata_alter_seocompetitor_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='brief_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='source_seo_opportunity_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='seo.seoopportunitysnapshot'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='source_seo_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='seo.seocontextsnapshot'),
        ),
    ]
