# Generated by Django 5.2.10 on 2026-03-29 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_generatedcontent_brief_json_and_more'),
        ('leads', '0007_alter_usagerecord_metric'),
        ('seo', '0005_seocompetitor_metadata_alter_seocompetitor_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEditorialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief_key', models.CharField(max_length=120)),
                ('brief_hash', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('output_type', models.CharField(choices=[('service_page', 'Service Page'), ('landing_page', 'Landing Page'), ('article', 'Article'), ('answer_block', 'Answer Block')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('drafted', 'Drafted'), ('applied', 'Applied'), ('stale', 'Stale'), ('archived', 'Archived')], default='queued', max_length=16)),
                ('priority_score', models.PositiveSmallIntegerField(default=0)),
                ('brief_json', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('latest_generated_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_task_links', to='content.generatedcontent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_tasks', to='leads.clientproject')),
                ('source_seo_opportunity_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_tasks', to='seo.seoopportunitysnapshot')),
                ('source_seo_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_tasks', to='seo.seocontextsnapshot')),
            ],
            options={
                'ordering': ('-priority_score', '-updated_at'),
            },
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='source_editorial_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_drafts', to='content.contenteditorialtask'),
        ),
        migrations.AddConstraint(
            model_name='contenteditorialtask',
            constraint=models.UniqueConstraint(fields=('project', 'brief_key'), name='unique_editorial_task_per_project_brief'),
        ),
    ]
