# Generated by Django 5.2.10 on 2026-04-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contenteditorialtask_and_more'),
        ('seo', '0007_seocampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenteditorialtask',
            name='seo_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_tasks', to='seo.seocampaign'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='source_seo_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='seo.seocampaign'),
        ),
    ]
