# Generated by Django 5.2.10 on 2026-05-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_contenteditorialtask_seo_campaign_and_more'),
        ('leads', '0013_workspacemembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('wordpress', 'WordPress'), ('webflow', 'Webflow')], default='wordpress', max_length=24)),
                ('site_url', models.URLField(help_text='WordPress site URL (e.g. https://yourdomain.com).')),
                ('username', models.CharField(blank=True, help_text='WordPress username (only for password-auth).', max_length=120)),
                ('app_password', models.CharField(blank=True, help_text='WordPress Application Password (stored verbatim; treat as secret).', max_length=255)),
                ('api_token', models.CharField(blank=True, help_text='Webflow API token (when platform=webflow).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_credentials', to='leads.clientproject')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CMSPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('remote_post_id', models.CharField(blank=True, max_length=64)),
                ('remote_post_url', models.URLField(blank=True)),
                ('response_summary', models.TextField(blank=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_logs', to='content.cmscredential')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='content.contenteditorialtask')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_push_triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='cmscredential',
            constraint=models.UniqueConstraint(fields=('project', 'platform'), name='unique_cms_credential_per_platform_per_project'),
        ),
    ]
