# Generated by Django 5.2.10 on 2026-03-26 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_type', models.CharField(choices=[('seo', 'SEO Audit'), ('aeo', 'AEO Audit'), ('combined', 'Combined Audit')], default='combined', max_length=24)),
                ('normalized_domain', models.CharField(max_length=255)),
                ('start_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('technical_score', models.PositiveSmallIntegerField(default=0)),
                ('on_page_score', models.PositiveSmallIntegerField(default=0)),
                ('content_score', models.PositiveSmallIntegerField(default=0)),
                ('aeo_score', models.PositiveSmallIntegerField(default=0)),
                ('internal_linking_score', models.PositiveSmallIntegerField(default=0)),
                ('performance_score', models.PositiveSmallIntegerField(default=0)),
                ('pages_crawled', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('audit_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_runs', to='leads.auditrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('h1', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(blank=True, max_length=255)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('internal_link_count', models.PositiveSmallIntegerField(default=0)),
                ('images_missing_alt', models.PositiveSmallIntegerField(default=0)),
                ('schema_count', models.PositiveSmallIntegerField(default=0)),
                ('has_faq_schema', models.BooleanField(default=False)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tools.auditrun')),
            ],
            options={
                'ordering': ('url',),
            },
        ),
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('on_page', 'On-page'), ('content', 'Content'), ('aeo', 'AEO'), ('internal_linking', 'Internal Linking'), ('performance', 'Performance')], max_length=24)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('message', models.CharField(max_length=255)),
                ('recommendation', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='tools.auditpage')),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='tools.auditrun')),
            ],
            options={
                'ordering': ('severity', 'category', 'created_at'),
            },
        ),
    ]
