# Generated by Django 5.2.10 on 2026-03-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auditrun_auditpage_auditissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpage',
            name='pagespeed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditpage',
            name='pagespeed_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
