# Generated by Django 5.2.10 on 2026-03-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auditpage_pagespeed_data_auditpage_pagespeed_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpage',
            name='asset_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditpage',
            name='readability_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditpage',
            name='security_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditpage',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
