# Generated by Django 5.2.10 on 2026-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auditpage_asset_stats_auditpage_readability_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditpage',
            name='accessibility_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditpage',
            name='best_practices_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditpage',
            name='seo_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
