# Generated by Django 5.2.10 on 2026-03-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auditpage_accessibility_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrun',
            name='accessibility_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='best_practices_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='seo_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='tech_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
