# Generated by Django 5.2.10 on 2026-03-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_workspaceplan_workspacesubscription_usagerecord'),
        ('tools', '0006_auditrun_accessibility_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChangeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score_delta', models.IntegerField(default=0)),
                ('pages_crawled_delta', models.IntegerField(default=0)),
                ('new_issue_count', models.PositiveIntegerField(default=0)),
                ('resolved_issue_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('audit_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_report', to='tools.auditrun')),
                ('previous_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_change_reports', to='tools.auditrun')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_reports', to='leads.clientproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAuditSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to='tools.auditrun')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_schedule', to='leads.clientproject')),
            ],
            options={
                'ordering': ('project__name',),
            },
        ),
    ]
