# Generated by Django 5.2.10 on 2026-03-29 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auditchangereport_workspaceauditschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceauditschedule',
            name='alert_on_new_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceauditschedule',
            name='alert_on_score_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceauditschedule',
            name='email_reports_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceauditschedule',
            name='report_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AuditShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='tools.auditrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
