# Generated by Django 5.2.10 on 2026-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='VRT SPACE AGENCY', max_length=120)),
                ('hero_title', models.CharField(default='Make your brand the source AI search trusts.', max_length=255)),
                ('hero_subtitle', models.TextField(default='Build a high-performance SEO and AEO platform that ranks on Google, wins citations in AI answers, and turns authority into inbound leads.')),
                ('proprietary_method_name', models.CharField(default='VRT Authority Engine', max_length=120)),
                ('primary_cta_label', models.CharField(default='Request a Free AEO Audit', max_length=80)),
                ('secondary_cta_label', models.CharField(default='Talk to a Strategist', max_length=80)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
