# Generated by Django 5.2.10 on 2026-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('gemini', 'Gemini'), ('perplexity', 'Perplexity')], max_length=24)),
                ('prompt', models.TextField()),
                ('cited_url', models.URLField(blank=True)),
                ('answer_present', models.BooleanField(default=False)),
                ('citation_frequency', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('engine', '-created_at'),
            },
        ),
    ]
