# Generated by Django 5.2.10 on 2026-03-29 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeo', '0001_initial'),
        ('leads', '0007_alter_usagerecord_metric'),
        ('seo', '0002_seoprojectprofile_seocontextsnapshot'),
        ('tools', '0008_workspaceauditschedule_alert_on_new_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEOAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_keyword', models.CharField(blank=True, max_length=160)),
                ('visibility_score', models.PositiveSmallIntegerField(default=0)),
                ('entity_score', models.PositiveSmallIntegerField(default=0)),
                ('structure_score', models.PositiveSmallIntegerField(default=0)),
                ('completeness_score', models.PositiveSmallIntegerField(default=0)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeo_audits', to='leads.clientproject')),
                ('seo_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aeo_audits', to='seo.seoprojectprofile')),
                ('source_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aeo_audits', to='tools.auditrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.CharField(max_length=255)),
                ('why_ai_ignores_this', models.TextField(blank=True)),
                ('fix', models.TextField(blank=True)),
                ('example_rewrite', models.TextField(blank=True)),
                ('expected_impact', models.TextField(blank=True)),
                ('priority_score', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('aeo_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='aeo.aeoaudit')),
            ],
            options={
                'ordering': ('-priority_score', 'created_at'),
            },
        ),
    ]
