# Generated by Django 5.2.10 on 2026-04-12 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeo', '0002_aeoaudit_airecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='visibilitysnapshot',
            name='aeo_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visibility_snapshots', to='aeo.aeoaudit'),
        ),
    ]
