# Generated by Django 5.2.10 on 2026-05-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeo', '0003_visibilitysnapshot_aeo_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeoaudit',
            name='competitor_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aeoaudit',
            name='engines_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aeoaudit',
            name='precision_mode',
            field=models.CharField(default='derived', help_text="'derived' = on-page heuristic; 'live' = real LLM API calls", max_length=16),
        ),
        migrations.AddField(
            model_name='aeoaudit',
            name='queries_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aeoaudit',
            name='queries_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aeoaudit',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aeoaudit',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aeoaudit',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16),
        ),
    ]
