# Generated by Django 5.2.10 on 2026-05-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeo', '0004_aeoaudit_competitor_visibility_aeoaudit_engines_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEOIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('chatgpt_cited', models.BooleanField(default=False)),
                ('gemini_cited', models.BooleanField(default=False)),
                ('perplexity_cited', models.BooleanField(default=False)),
                ('chatgpt_frequency', models.PositiveSmallIntegerField(default=0)),
                ('gemini_frequency', models.PositiveSmallIntegerField(default=0)),
                ('perplexity_frequency', models.PositiveSmallIntegerField(default=0)),
                ('queries_log', models.JSONField(blank=True, default=list)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('lookup_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'AEO index entries',
                'ordering': ('-last_checked_at', '-created_at'),
            },
        ),
    ]
