# Generated by Django 5.2.10 on 2026-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeo', '0005_aeoindexentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeoindexentry',
            name='overall_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
