# Generated by Django 5.2.10 on 2026-05-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeo', '0006_aeoindexentry_overall_score'),
        ('leads', '0013_workspacemembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.CharField(max_length=300)),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('comparison', 'Comparison'), ('local', 'Local'), ('brand', 'Brand')], default='informational', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_target_cited', models.BooleanField(default=False)),
                ('last_share_of_voice', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_prompts', to='leads.clientproject')),
            ],
            options={
                'ordering': ('-is_active', '-last_checked_at', 'prompt'),
            },
        ),
        migrations.CreateModel(
            name='PromptCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('gemini', 'Gemini'), ('perplexity', 'Perplexity')], max_length=24)),
                ('target_cited', models.BooleanField(default=False)),
                ('target_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('answer_snippet', models.TextField(blank=True)),
                ('cited_brands', models.JSONField(blank=True, default=list)),
                ('competitor_brands', models.JSONField(blank=True, default=list)),
                ('citation_score', models.PositiveSmallIntegerField(default=0)),
                ('sentiment', models.CharField(default='neutral', max_length=16)),
                ('raw_signals', models.JSONField(blank=True, default=dict)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='aeo.trackedprompt')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrackedCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=120)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#818cf8', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_competitors', to='leads.clientproject')),
            ],
            options={
                'ordering': ('-is_active', 'brand_name'),
                'constraints': [models.UniqueConstraint(fields=('project', 'brand_name'), name='unique_competitor_per_project')],
            },
        ),
        migrations.AddConstraint(
            model_name='trackedprompt',
            constraint=models.UniqueConstraint(fields=('project', 'prompt'), name='unique_prompt_per_project'),
        ),
        migrations.AddIndex(
            model_name='promptcheckrun',
            index=models.Index(fields=['prompt', 'engine', '-created_at'], name='aeo_promptc_prompt__a6a14f_idx'),
        ),
    ]
