# Generated by Django 5.2.10 on 2026-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('monthly_leads_goal', models.PositiveIntegerField(default=20)),
                ('notes', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('qualified', 'Qualified')], default='new', max_length=16)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('website', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('interest_area', models.CharField(choices=[('aeo', 'Answer Engine Optimization'), ('seo', 'SEO'), ('content', 'Content Marketing'), ('web', 'Web Development')], max_length=24)),
                ('source_page', models.CharField(blank=True, max_length=255)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
