# Generated by Django 5.2.10 on 2026-03-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        existing_tables = set(schema_editor.connection.introspection.table_names())
        if model._meta.db_table in existing_tables:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        existing_tables = set(schema_editor.connection.introspection.table_names())
        if model._meta.db_table not in existing_tables:
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('tools', '0006_auditrun_accessibility_score_and_more'),
    ]

    operations = [
        CreateModelIfMissing(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('website', models.URLField()),
                ('normalized_domain', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('stage', models.CharField(choices=[('discovery', 'Discovery'), ('proposal', 'Proposal'), ('active', 'Active'), ('retained', 'Retained'), ('archived', 'Archived')], default='discovery', max_length=16)),
                ('latest_score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('audit_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_project', to='leads.auditrequest')),
                ('latest_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshots', to='tools.auditrun')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
