# Generated by Django 5.2.10 on 2026-03-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_clientproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrequest',
            name='submission_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='submission_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
