# Generated by Django 5.2.10 on 2026-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_workspaceplan_workspacesubscription_usagerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrequest',
            name='competitor_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='market_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspaceplan',
            name='competitor_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceplan',
            name='email_reports_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceplan',
            name='stakeholder_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
