# Generated by Django 5.2.10 on 2026-03-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auditrequest_competitor_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagerecord',
            name='metric',
            field=models.CharField(choices=[('audit_run', 'Audit Run'), ('seo_snapshot', 'SEO Snapshot'), ('aeo_audit', 'AEO Audit'), ('export', 'Export')], max_length=32),
        ),
    ]
