# Generated by Django 5.2.10 on 2026-04-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_usagerecord_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrequest',
            name='business_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='primary_service',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='target_goal',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='business_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='primary_service',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='target_goal',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
