# Generated by Django 5.2.10 on 2026-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_workspacecreditledger_and_plan_credit_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacecreditledger',
            name='category',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('audit', 'Audit'), ('seo', 'SEO'), ('aeo', 'AEO'), ('content', 'Content'), ('backlink', 'Backlink'), ('export', 'Export'), ('share', 'Share')], max_length=24),
        ),
    ]
