# Generated by Django 5.2.10 on 2026-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_workspacecreditledger_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrequest',
            name='business_subtype',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='location_area',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='location_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='location_mode',
            field=models.CharField(blank=True, default='targeted', max_length=24),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='location_scope',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='business_subtype',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='location_area',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='location_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='location_mode',
            field=models.CharField(blank=True, default='targeted', max_length=24),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='location_scope',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
