# Generated by Django 5.2.10 on 2026-05-09 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0011_auditrequest_business_subtype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("threshold_pct", models.PositiveSmallIntegerField()),
                ("used_at_alert", models.PositiveIntegerField(default=0)),
                ("granted_at_alert", models.PositiveIntegerField(default=0)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "In-app"),
                            ("both", "Both"),
                        ],
                        default="email",
                        max_length=12,
                    ),
                ),
                ("delivered", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_alerts",
                        to="leads.workspacesubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-period_start", "-threshold_pct", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "period_start", "threshold_pct"),
                        name="uniq_credit_alert_per_user_period_threshold",
                    )
                ],
            },
        ),
    ]
