# Generated by Django 5.2.10 on 2026-05-27 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0013_workspacemembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSCConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("google_email", models.EmailField(blank=True, max_length=254)),
                ("sc_property", models.CharField(blank=True, max_length=512)),
                ("refresh_token", models.TextField(blank=True)),
                ("access_token", models.TextField(blank=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_connection",
                        to="leads.clientproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "GSC Connection",
                "verbose_name_plural": "GSC Connections",
            },
        ),
    ]
