from io import BytesIO
from textwrap import wrap


SECTION_DIVIDER = "-" * 76


def _escape_pdf_text(value):
    return str(value).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _build_report_lines(payload):
    project = payload.get("project", {})
    profile = payload.get("profile", {})
    benchmark_summary = payload.get("benchmark_summary", {})
    recommendations = payload.get("recommendations", [])
    execution_queue = payload.get("execution_queue", [])
    campaigns = payload.get("campaigns", [])
    backlink_summary = payload.get("backlink_summary", {})
    backlink_prospects = payload.get("backlink_prospects", [])
    competitor_trace = payload.get("competitor_trace", [])

    lines = [
        "VRT SPACE AGENCY",
        "Stakeholder SEO Report",
        SECTION_DIVIDER,
        f"Project: {project.get('name', '')}",
        f"Domain: {project.get('domain', '')}",
        f"Business type: {profile.get('business_type', '')}",
        f"Location: {profile.get('location', '')}",
        f"Primary service: {profile.get('primary_service', '')}",
        f"Goal: {profile.get('target_goal', '')}",
        "",
        "Executive summary",
        SECTION_DIVIDER,
        f"This SEO strategy report freezes the current benchmark state for {project.get('domain', '')}.",
        f"Competitors benchmarked: {benchmark_summary.get('available_competitors', 0)}",
        f"Discovery precision: {benchmark_summary.get('average_relevance', 0)}",
        f"Execution items: {payload.get('value_summary', {}).get('execution_items', 0)}",
        "",
        "Benchmark decision trace",
        SECTION_DIVIDER,
    ]

    for item in competitor_trace[:8]:
        lines.append(
            f"- {item.get('domain')}: {item.get('final_decision_label', '')} | "
            f"Pages profiled: {item.get('page_count', 0)} | Best score: {item.get('fit', {}).get('best_page_score', 0)}"
        )
        if item.get("fit", {}).get("reason"):
            lines.append(f"  Reason: {item['fit']['reason']}")
        if item.get("queries"):
            lines.append(f"  Queries: {', '.join(item.get('queries', [])[:3])}")

    lines.extend(["", "Priority recommendations", SECTION_DIVIDER])
    for index, item in enumerate(recommendations[:8], start=1):
        lines.append(f"{index}. {item.get('title', 'Recommendation')}")
        if item.get("why_it_matters"):
            lines.append(f"   Why it matters: {item['why_it_matters']}")
        if item.get("recommended_fix"):
            lines.append(f"   Fix: {item['recommended_fix']}")

    lines.extend(["", "Execution queue", SECTION_DIVIDER])
    for index, item in enumerate(execution_queue[:8], start=1):
        lines.append(f"{index}. {item.get('title', 'Execution item')} | {item.get('deliverable', '')}")
        if item.get("target_urls"):
            lines.append(f"   Where to apply: {', '.join(item.get('target_urls', [])[:3])}")
        if item.get("action_steps"):
            for step in item.get("action_steps", [])[:3]:
                lines.append(f"   Step: {step}")

    lines.extend(["", "Campaign pipeline", SECTION_DIVIDER])
    for item in campaigns[:8]:
        lines.append(
            f"- {item.get('title', '')}: {item.get('status', '')} | "
            f"Validation: {item.get('validation_status', '')} | Draft: {item.get('draft_title') or 'Not created'}"
        )
        if item.get("target_keyword"):
            lines.append(f"  Target keyword: {item['target_keyword']}")
        lines.append(
            f"  Outreach targets: {item.get('backlink_prospect_count', 0)} | Acquired links: {item.get('acquired_backlink_count', 0)}"
        )

    lines.extend(
        [
            "",
            "Backlink strategy",
            SECTION_DIVIDER,
            f"Linkable assets: {backlink_summary.get('linkable_asset_count', 0)}",
            f"Prospects discovered: {backlink_summary.get('prospect_count', 0)}",
            f"Average prospect score: {backlink_summary.get('average_total_score', 0)}",
        ]
    )
    for item in backlink_prospects[:8]:
        lines.append(
            f"- {item.get('domain', '')}: {item.get('prospect_type', '')} | Score {item.get('total_score', 0)} | Target: {item.get('target_asset_title', '')}"
        )

    lines.extend(
        [
            "",
            SECTION_DIVIDER,
            "Generated by VRT SPACE AGENCY",
            "This report is based on the saved SEO benchmark, opportunity, and backlink snapshots.",
        ]
    )
    return lines


def _paginate_lines(lines, *, width=92, lines_per_page=44):
    wrapped_lines = []
    for line in lines:
        if not line:
            wrapped_lines.append("")
            continue
        wrapped_lines.extend(wrap(line, width=width) or [""])

    pages = []
    for start in range(0, len(wrapped_lines), lines_per_page):
        pages.append(wrapped_lines[start:start + lines_per_page])
    return pages or [[]]


def _build_pdf_bytes(page_lines):
    buffer = BytesIO()
    offsets = []

    def write(value):
        if isinstance(value, str):
            value = value.encode("latin-1", errors="replace")
        buffer.write(value)

    write("%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")

    page_count = len(page_lines)
    font_object_id = 3 + (page_count * 2)

    def write_object(object_id, content):
        offsets.append(buffer.tell())
        write(f"{object_id} 0 obj\n")
        write(content)
        write("\nendobj\n")

    kids_refs = " ".join(f"{2 + (index * 2)} 0 R" for index in range(page_count))
    write_object(1, f"<< /Type /Pages /Count {page_count} /Kids [{kids_refs}] >>")

    content_object_ids = []
    for index, _lines in enumerate(page_lines):
        page_object_id = 2 + (index * 2)
        content_object_id = page_object_id + 1
        content_object_ids.append(content_object_id)
        write_object(
            page_object_id,
            (
                f"<< /Type /Page /Parent 1 0 R /MediaBox [0 0 612 792] "
                f"/Resources << /Font << /F1 {font_object_id} 0 R >> >> "
                f"/Contents {content_object_id} 0 R >>"
            ),
        )

    for content_object_id, lines in zip(content_object_ids, page_lines):
        text_commands = ["BT", "/F1 11 Tf", "50 760 Td", "14 TL"]
        for line in lines:
            text_commands.append(f"({_escape_pdf_text(line)}) Tj")
            text_commands.append("T*")
        text_commands.append("ET")
        stream = "\n".join(text_commands)
        write_object(
            content_object_id,
            f"<< /Length {len(stream.encode('latin-1', errors='replace'))} >>\nstream\n{stream}\nendstream",
        )

    write_object(font_object_id, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    catalog_object_id = font_object_id + 1
    write_object(catalog_object_id, "<< /Type /Catalog /Pages 1 0 R >>")

    xref_start = buffer.tell()
    write(f"xref\n0 {catalog_object_id + 1}\n")
    write("0000000000 65535 f \n")
    for offset in offsets:
        write(f"{offset:010d} 00000 n \n")

    write(
        f"trailer\n<< /Size {catalog_object_id + 1} /Root {catalog_object_id} 0 R >>\n"
        f"startxref\n{xref_start}\n%%EOF"
    )
    return buffer.getvalue()


def build_seo_report_pdf(payload):
    lines = _build_report_lines(payload)
    pages = _paginate_lines(lines)
    return _build_pdf_bytes(pages)
