# Generated by Django 5.2.10 on 2026-03-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auditrequest_competitor_urls_and_more'),
        ('seo', '0001_initial'),
        ('tools', '0008_workspaceauditschedule_alert_on_new_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=160)),
                ('target_goal', models.CharField(max_length=160)),
                ('primary_service', models.CharField(blank=True, max_length=160)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_profile', to='leads.clientproject')),
            ],
            options={
                'ordering': ('project__name',),
            },
        ),
        migrations.CreateModel(
            name='SEOContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_snapshots', to='leads.clientproject')),
                ('source_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_snapshots', to='tools.auditrun')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='seo.seoprojectprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
