# Generated by Django 5.2.10 on 2026-03-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_usagerecord_metric'),
        ('seo', '0002_seoprojectprofile_seocontextsnapshot'),
        ('tools', '0008_workspaceauditschedule_alert_on_new_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homepage_url', models.URLField()),
                ('normalized_domain', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('source', models.CharField(choices=[('audit', 'Audit'), ('profile', 'Profile')], default='profile', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_competitors', to='leads.clientproject')),
            ],
            options={
                'ordering': ('project__name', 'homepage_url'),
            },
        ),
        migrations.CreateModel(
            name='SEOCompetitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='seo.seocompetitor')),
                ('source_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_competitor_snapshots', to='tools.auditrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SEOSiteStructureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_site_structure_snapshots', to='leads.clientproject')),
                ('source_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_site_structure_snapshots', to='tools.auditrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='seocompetitor',
            constraint=models.UniqueConstraint(fields=('project', 'homepage_url'), name='unique_project_seo_competitor'),
        ),
    ]
