# Generated by Django 5.2.10 on 2026-03-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_usagerecord_metric'),
        ('seo', '0003_seocompetitor_seocompetitorsnapshot_and_more'),
        ('tools', '0008_workspaceauditschedule_alert_on_new_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOOpportunitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_snapshots', to='seo.seoprojectprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_opportunity_snapshots', to='leads.clientproject')),
                ('source_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_opportunity_snapshots', to='tools.auditrun')),
                ('source_context_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_snapshots', to='seo.seocontextsnapshot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
