# Generated by Django 5.2.10 on 2026-03-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_seoopportunitysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocompetitor',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='seocompetitor',
            name='source',
            field=models.CharField(choices=[('audit', 'Audit'), ('profile', 'Profile'), ('serp', 'SERP Discovery')], default='profile', max_length=24),
        ),
    ]
