# Generated by Django 5.2.10 on 2026-03-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_usagerecord_metric'),
        ('seo', '0005_seocompetitor_metadata_alter_seocompetitor_source'),
        ('tools', '0008_workspaceauditschedule_alert_on_new_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklinkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlink_snapshots', to='seo.seoprojectprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlink_snapshots', to='leads.clientproject')),
                ('source_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlink_snapshots', to='tools.auditrun')),
                ('source_context_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlink_snapshots', to='seo.seocontextsnapshot')),
                ('source_opportunity_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlink_snapshots', to='seo.seoopportunitysnapshot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BacklinkProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('homepage_url', models.URLField(blank=True)),
                ('prospect_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('prospect_type', models.CharField(choices=[('resource', 'Resource Page'), ('directory', 'Directory / Citation'), ('association', 'Association'), ('blog', 'Blog / Publication'), ('media', 'Media / Press'), ('partner', 'Partner')], default='resource', max_length=24)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('shortlisted', 'Shortlisted'), ('outreached', 'Outreached'), ('replied', 'Replied'), ('acquired', 'Acquired'), ('rejected', 'Rejected')], default='suggested', max_length=24)),
                ('relevance_score', models.PositiveSmallIntegerField(default=0)),
                ('authority_fit_score', models.PositiveSmallIntegerField(default=0)),
                ('local_fit_score', models.PositiveSmallIntegerField(default=0)),
                ('outreach_likelihood_score', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('target_asset_title', models.CharField(blank=True, max_length=255)),
                ('target_asset_type', models.CharField(blank=True, max_length=120)),
                ('target_asset_url', models.URLField(blank=True)),
                ('suggested_anchor_text', models.CharField(blank=True, max_length=255)),
                ('outreach_packet', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlink_prospects', to='leads.clientproject')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='seo.backlinksnapshot')),
            ],
            options={
                'ordering': ('-total_score', '-updated_at'),
                'constraints': [models.UniqueConstraint(fields=('project', 'prospect_url', 'target_asset_url'), name='unique_backlink_prospect_per_target')],
            },
        ),
    ]
