# Generated by Django 5.2.10 on 2026-04-01 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auditrequest_business_type_auditrequest_location_and_more'),
        ('seo', '0006_backlinksnapshot_backlinkprospect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_key', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=255)),
                ('page_type', models.CharField(blank=True, max_length=80)),
                ('target_keyword', models.CharField(blank=True, max_length=255)),
                ('related_keywords', models.JSONField(blank=True, default=list)),
                ('related_page_urls', models.JSONField(blank=True, default=list)),
                ('success_criteria', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('archived', 'Archived')], default='queued', max_length=20)),
                ('priority_score', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_campaigns', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_campaigns', to='leads.clientproject')),
                ('source_context_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='seo.seocontextsnapshot')),
                ('source_opportunity_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='seo.seoopportunitysnapshot')),
            ],
            options={
                'ordering': ('status', '-priority_score', '-updated_at'),
                'constraints': [models.UniqueConstraint(fields=('project', 'campaign_key'), name='unique_seo_campaign_per_project_key')],
            },
        ),
    ]
