# Generated by Django 5.2.10 on 2026-04-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_seocampaign'),
        ('tools', '0008_workspaceauditschedule_alert_on_new_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlinkprospect',
            name='seo_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlink_prospects', to='seo.seocampaign'),
        ),
        migrations.AddField(
            model_name='seocampaign',
            name='latest_validation_audit_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_seo_campaigns', to='tools.auditrun'),
        ),
        migrations.AddField(
            model_name='seocampaign',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated')], default='pending', max_length=20),
        ),
    ]
