# Generated by Django 5.2.10 on 2026-05-27 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0009_seosharelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOCampaignEditItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_url", models.CharField(blank=True, max_length=2000)),
                ("page_title", models.CharField(blank=True, max_length=255)),
                ("page_type", models.CharField(blank=True, max_length=80)),
                ("change_scope", models.CharField(blank=True, max_length=40)),
                ("changes", models.JSONField(default=list)),
                ("success_criteria", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=dict)),
                ("ordering_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_items",
                        to="seo.seocampaign",
                    ),
                ),
            ],
            options={
                "ordering": ("ordering_index", "status"),
            },
        ),
    ]
