# Generated by Django 5.2.10 on 2026-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=120)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.TextField()),
                ('key_metric', models.CharField(max_length=120)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'case studies',
                'ordering': ('-featured', '-created_at'),
            },
        ),
    ]
