from io import BytesIO
from textwrap import wrap


def _escape_pdf_text(value):
    return (
        str(value)
        .replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
    )


def _build_report_lines(audit_run):
    summary = audit_run.summary or {}
    score_breakdown = summary.get("score_breakdown", {})
    recommendations = summary.get("recommendations", [])
    issue_summary = summary.get("issue_summary", {})
    pagespeed = summary.get("pagespeed", {})

    lines = [
        "VRT SPACE Audit Report",
        f"Domain: {audit_run.normalized_domain}",
        f"Status: {audit_run.get_status_display()}",
        f"Overall score: {audit_run.overall_score}",
        f"Pages crawled: {audit_run.pages_crawled}",
        f"Completed at: {audit_run.completed_at or 'Pending'}",
        "",
        "Score breakdown",
    ]

    for key in ("technical", "on_page", "content", "aeo", "internal_linking", "performance"):
        item = score_breakdown.get(key)
        if not item:
            continue
        lines.append(
            f"- {item.get('label', key.title())}: {item.get('score', 0)} | "
            f"Status: {item.get('status', 'n/a')} | Issues: {item.get('issues', 0)}"
        )
        next_step = item.get("next_step")
        if next_step:
            lines.append(f"  Next step: {next_step}")

    if pagespeed:
        lines.extend(
            [
                "",
                "PageSpeed summary",
                f"- Source: {pagespeed.get('source', 'Unknown')}",
                f"- Strategy: {pagespeed.get('strategy', 'Unknown')}",
            ]
        )
        for metric, value in (pagespeed.get("metrics") or {}).items():
            label = metric.replace("_", " ").title()
            lines.append(f"- {label}: {value}")

    lines.extend(
        [
            "",
            "Issue summary",
            f"- Total issues: {issue_summary.get('total', 0)}",
        ]
    )
    for category, count in sorted((issue_summary.get("by_category") or {}).items()):
        lines.append(f"- {category.replace('_', ' ').title()}: {count}")

    lines.extend(["", "Priority recommendations"])
    for index, recommendation in enumerate(recommendations[:8], start=1):
        lines.append(
            f"{index}. {recommendation.get('title', 'Recommendation')} "
            f"({recommendation.get('category', 'General')}, priority {recommendation.get('priority_score', 0)})"
        )
        description = recommendation.get("description")
        if description:
            lines.append(f"   {description}")
        fix = recommendation.get("recommended_fix")
        if fix:
            lines.append(f"   Fix: {fix}")
        impact = recommendation.get("estimated_impact")
        if impact:
            lines.append(f"   Impact: {impact}")

    lines.extend(
        [
            "",
            "Generated by VRT SPACE AGENCY",
            "This report is based on the stored audit result and can be shared with internal teams or stakeholders.",
        ]
    )
    return lines


def _paginate_lines(lines, *, width=92, lines_per_page=44):
    wrapped_lines = []
    for line in lines:
        if not line:
            wrapped_lines.append("")
            continue
        wrapped_lines.extend(wrap(line, width=width) or [""])

    pages = []
    for start in range(0, len(wrapped_lines), lines_per_page):
        pages.append(wrapped_lines[start:start + lines_per_page])
    return pages or [[]]


def _build_pdf_bytes(page_lines):
    buffer = BytesIO()
    offsets = []

    def write(value):
        if isinstance(value, str):
            value = value.encode("latin-1", errors="replace")
        buffer.write(value)

    write("%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")

    page_count = len(page_lines)
    font_object_id = 3 + (page_count * 2)

    def write_object(object_id, content):
        offsets.append(buffer.tell())
        write(f"{object_id} 0 obj\n")
        write(content)
        write("\nendobj\n")

    kids_refs = " ".join(f"{2 + (index * 2)} 0 R" for index in range(page_count))
    write_object(1, f"<< /Type /Pages /Count {page_count} /Kids [{kids_refs}] >>")

    content_object_ids = []
    for index, lines in enumerate(page_lines):
        page_object_id = 2 + (index * 2)
        content_object_id = page_object_id + 1
        content_object_ids.append(content_object_id)
        write_object(
            page_object_id,
            (
                f"<< /Type /Page /Parent 1 0 R /MediaBox [0 0 612 792] "
                f"/Resources << /Font << /F1 {font_object_id} 0 R >> >> "
                f"/Contents {content_object_id} 0 R >>"
            ),
        )

    for content_object_id, lines in zip(content_object_ids, page_lines):
        text_commands = ["BT", "/F1 11 Tf", "50 760 Td", "14 TL"]
        for line in lines:
            text_commands.append(f"({_escape_pdf_text(line)}) Tj")
            text_commands.append("T*")
        text_commands.append("ET")
        stream = "\n".join(text_commands)
        write_object(
            content_object_id,
            f"<< /Length {len(stream.encode('latin-1', errors='replace'))} >>\nstream\n{stream}\nendstream",
        )

    write_object(font_object_id, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    catalog_object_id = font_object_id + 1
    write_object(catalog_object_id, "<< /Type /Catalog /Pages 1 0 R >>")

    xref_start = buffer.tell()
    write(f"xref\n0 {catalog_object_id + 1}\n")
    write("0000000000 65535 f \n")
    for offset in offsets:
        write(f"{offset:010d} 00000 n \n")

    write(
        f"trailer\n<< /Size {catalog_object_id + 1} /Root {catalog_object_id} 0 R >>\n"
        f"startxref\n{xref_start}\n%%EOF"
    )
    return buffer.getvalue()


def build_audit_report_pdf(audit_run):
    lines = _build_report_lines(audit_run)
    pages = _paginate_lines(lines)
    return _build_pdf_bytes(pages)
