from django.urls import path, re_path

from .billing_views import (
    StripeWebhookView,
    WorkspaceAuditRerunView,
    WorkspaceAuditScheduleView,
    WorkspaceBillingCancelView,
    WorkspaceBillingPortalView,
    WorkspaceBillingSuccessView,
    WorkspaceCheckoutCreateView,
    WorkspaceTopupCreateView,
)
from .views import (
    AgencyAuditDetailView,
    WorkspaceDemoView,
    AccountDashboardView,
    AccountPasswordUpdateView,
    AccountProfileUpdateView,
    AuditResultDetailView,
    AuditReportPdfView,
    GoogleOAuthCallbackView,
    GoogleOAuthStartView,
    ProjectDashboardDetailView,
    PublicAuditCreateView,
    WorkspaceDashboardView,
    WorkspaceAuditStartView,
    WorkspaceAuditExportCsvView,
    WorkspaceAuditExportJsonView,
    WorkspaceAuditShareCreateView,
    WorkspaceLoginView,
    WorkspaceLogoutView,
    WorkspaceOnboardingView,
    WorkspaceOnboardingStep1View,
    WorkspaceOnboardingStep2View,
    WorkspaceOnboardingAuditPollView,
    WorkspaceOnboardingStep3View,
    WorkspaceOnboardingCompleteView,
    WorkspaceProjectCreateView,
    WorkspaceProjectSelectView,
    WorkspaceSignupView,
    WorkspaceWelcomeView,
    SharedAuditReportPdfView,
    SharedAuditReportView,
    WorkspaceAgencyDashboardView,
)
from .team_views import (
    AcceptInviteView,
    ClientSharedProjectView,
    RevokeMemberView,
    WorkspaceTeamView,
)

app_name = "tools"

urlpatterns = [
    path("tools/free-seo-audit/", PublicAuditCreateView.as_view(), name="free-seo-audit"),
    path("tools/audits/<int:pk>/", AuditResultDetailView.as_view(), name="audit-result"),
    path("tools/audits/<int:pk>/report.pdf", AuditReportPdfView.as_view(), name="audit-report-pdf"),
    path("tools/agency/audits/<int:pk>/", AgencyAuditDetailView.as_view(), name="agency-audit"),
    path("tools/agency/projects/<int:pk>/", ProjectDashboardDetailView.as_view(), name="project-dashboard"),
    path("workspace/start/", WorkspaceSignupView.as_view(), name="workspace-signup"),
    path("workspace/login/", WorkspaceLoginView.as_view(), name="workspace-login"),
    path("workspace/logout/", WorkspaceLogoutView.as_view(), name="workspace-logout"),
    path("account/", AccountDashboardView.as_view(), name="account-dashboard"),
    path("account/profile/", AccountProfileUpdateView.as_view(), name="account-profile-update"),
    path("account/password/", AccountPasswordUpdateView.as_view(), name="account-password-update"),
    path("workspace/projects/create/", WorkspaceProjectCreateView.as_view(), name="workspace-project-create"),
    path("workspace/projects/select/", WorkspaceProjectSelectView.as_view(), name="workspace-project-select"),
    path("workspace/audits/start/", WorkspaceAuditStartView.as_view(), name="workspace-audit-start"),
    path("workspace/billing/checkout/", WorkspaceCheckoutCreateView.as_view(), name="workspace-billing-checkout"),
    path("workspace/billing/topup/", WorkspaceTopupCreateView.as_view(), name="workspace-billing-topup"),
    path("workspace/billing/portal/", WorkspaceBillingPortalView.as_view(), name="workspace-billing-portal"),
    path("workspace/billing/success/", WorkspaceBillingSuccessView.as_view(), name="workspace-billing-success"),
    path("workspace/billing/cancel/", WorkspaceBillingCancelView.as_view(), name="workspace-billing-cancel"),
    path("workspace/audits/rerun/", WorkspaceAuditRerunView.as_view(), name="workspace-audit-rerun"),
    path("workspace/audits/schedule/", WorkspaceAuditScheduleView.as_view(), name="workspace-audit-schedule"),
    path("workspace/audits/<int:pk>/export.json", WorkspaceAuditExportJsonView.as_view(), name="workspace-audit-export-json"),
    path("workspace/audits/<int:pk>/export.csv", WorkspaceAuditExportCsvView.as_view(), name="workspace-audit-export-csv"),
    path("workspace/audits/<int:pk>/share/", WorkspaceAuditShareCreateView.as_view(), name="workspace-audit-share"),
    path("auth/google/start/", GoogleOAuthStartView.as_view(), name="google-oauth-start"),
    path("auth/google/callback/", GoogleOAuthCallbackView.as_view(), name="google-oauth-callback"),
    re_path(r"^billing/stripe/webhook/?$", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("share/audits/<slug:token>/", SharedAuditReportView.as_view(), name="shared-audit-report"),
    path("share/audits/<slug:token>/report.pdf", SharedAuditReportPdfView.as_view(), name="shared-audit-report-pdf"),
    path("workspace/demo/", WorkspaceDemoView.as_view(), name="workspace-demo"),
    path("workspace/agency/", WorkspaceAgencyDashboardView.as_view(), name="workspace-agency-dashboard"),
    path("workspace/", WorkspaceDashboardView.as_view(), name="workspace-dashboard"),
    path("workspace/welcome/", WorkspaceWelcomeView.as_view(), name="workspace-welcome"),
    path("workspace/onboarding/", WorkspaceOnboardingView.as_view(), name="workspace-onboarding"),
    path("workspace/onboarding/step/1/", WorkspaceOnboardingStep1View.as_view(), name="workspace-onboarding-step1"),
    path("workspace/onboarding/step/2/", WorkspaceOnboardingStep2View.as_view(), name="workspace-onboarding-step2"),
    path("workspace/onboarding/step/2/status/<int:pk>/", WorkspaceOnboardingAuditPollView.as_view(), name="workspace-onboarding-audit-poll"),
    path("workspace/onboarding/step/3/", WorkspaceOnboardingStep3View.as_view(), name="workspace-onboarding-step3"),
    path("workspace/onboarding/complete/", WorkspaceOnboardingCompleteView.as_view(), name="workspace-onboarding-complete"),
    path("workspace/team/", WorkspaceTeamView.as_view(), name="workspace-team"),
    path("workspace/team/<int:pk>/revoke/", RevokeMemberView.as_view(), name="workspace-team-revoke"),
    path("workspace/invite/<str:token>/accept/", AcceptInviteView.as_view(), name="workspace-invite-accept"),
    path("share/clients/<str:token>/", ClientSharedProjectView.as_view(), name="client-shared-project"),
]
